### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by himurabattousa** [jaondayko/WolfHUD#12]
Application has crashed: C++ exception
mods/WolfHUD-master/lua/CustomHUD.lua:4277: bad argument #1 to 'gsub' (string expected, got nil)

SCRIPT STACK
set_ai_stopped() @mods/WolfHUD-master/lua/CustomHUD.lua:4277
set_should_stay() lib/units/player_team/teamaimovement.lua:348
lib/network/handlers/unitnetworkhandler.lua:3832

The situation was meltdown, just before I opened the box with the crowbar, I called my teammates and it crashed.
Usually I don't crash when I call my teammates, but sometimes I crash right after I call them.
Sometimes it happens even when I call the AI.
Sometimes it doesn't crash even if I call them a lot.

**Comment by jaondayko** [comment]
1) Are you using any other mods?
2) Does it only appear to happen on that map? (Meltdown)
3) Do you know any way to make it happen every time (Reproducible? If not, at least explain a way that would have a chance to result in it that you know about)

**Comment by himurabattousa** [comment]
thanks for getting back to me
1 yes
2 yes
3 i do not know

Application has crashed: C++ exception
mods/WolfHUD-master/lua/CustomHUD.lua:4277: bad argument #1 to 'gsub' (string expected, got nil)

SCRIPT STACK
set_ai_stopped() @mods/WolfHUD-master/lua/CustomHUD.lua:4277
set_should_stay() lib/units/player_team/teamaimovement.lua:348
lib/network/handlers/unitnetworkhandler.lua:3832

Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap     

its the same error message every time

**Comment by himurabattousa** [comment]
Crashes when I call the AI.

**Comment by himurabattousa** [comment]
CustomHUD.lua
teamaimovement.lua
unitnetworkhandler.lua
Are you saying that these are conflicting?
I did a filename search and found these
CustomHUD.lua is only used by WOLFHUD and
teamaimovement.lua is not used by any mod and
unitnetworkhandler.lua is used by the mods KEEPERS, BETTER ASSULT INDICATOR, DOWN COUNTER, and THE FIXES.
Maybe this is the reason.
Is it a good idea to delete the unitnetworkhandler.lua in WOLFHUD?

It doesn't particularly crash when playing MELTDOWN offline, it crashes mainly in multiplayer.
I think the AI might be doing something weird with people coming and going or something.
However, in other JOBs, it doesn't crash except when I call the AI.
Why does it only happen in MELTDOWN?

Translated with www.DeepL.com/Translator (free version)

**Comment by jaondayko** [comment]
This should be fixed. open up a new issue if it is not
