### ISSUE TITLE
Damage popups disapear after getting downed.

### ISSUE THREAD

**Issue by sirben99** [jaondayko/WolfHUD#13]
Hey!

I noticed that when getting downed or cuffed by a cloaker in crime spree, the damage number popups stop working completely. Im not sure what could cause this, maybe a mod conflict?

If you reguire more information please ask and ill be happy to profide!

Ben

**Comment by jaondayko** [comment]
Are you using any mods? Does it happen every time or occasionally? Any specific map or only in crime sprees? 

The more info the better!

**Comment by sirben99** [comment]
Hey!

I do use other mods, over 600 to be eccact (MAJORITY weapon mods)
It seems to happen every time
No specific map, i mostly only play crime spree so i cant say about no crime spree

If youd like, i can go and test this further with only WolfHud installed!

Ben

**Comment by sirben99** [comment]
Hey!

Okay so, after testing with only WolfHud, the bug doesent seem to happen. So its very likely a mod conflict. 
But since i have over 600 mods, going though them to see what could cause this minor bug isnt really worth it imo, since removing/adding mods in that pase could cause serious issues.

Ill remember next time to test more before submiting an issue, sorry about the trouble!

Ben

**Comment by jaondayko** [comment]
No problem. That is a lot of mods to test through and if you ever discover which mod is conflicting, drop the name of it here so we can note it for future users!

Closing this issue since it is not happening from WolfHud.
