### ISSUE TITLE
Playing status language translation fix?

### ISSUE THREAD

**Issue by kotoricon** [jaondayko/WolfHUD#17]
The original wolfhud broken the steam playing status language support for each language, this also happen here.
It always show it like this: 

Lobby: XXX (HARD)
...
Playing XXX (EASY)
...
Payday XXX (DEATH SENTENCE)
...

This also broke that show how many player in your lobby or playing, and language always lock shown as english. any fix to restore origin game style shown as your local language and how many player in your status?

![1](https://user-images.githubusercontent.com/8659834/128040360-db69164a-7546-4e5b-a854-7acaa08b72fc.jpg)
![2](https://user-images.githubusercontent.com/8659834/128040373-636b0c83-c3ae-418b-89c5-1f3909284aea.jpg)

**Comment by jaondayko** [comment]
This is located in:
 WolfHUD/lua/RichPresence.lua 

We may have to look into a way to change it to use the loc files
