### ISSUE TITLE
damage popups show double damage and kills count as two

### ISSUE THREAD

**Issue by jsmoment** [jaondayko/WolfHUD#18]
# Expected Behavior
the popups will show the damage dealt and the kill counter will count kills correctly

# Current Behavior
the popups show double the damage dealt and when you get a kill the counter goes up by two

# Failure Information (for bugs)
## Steps to Reproduce
1. enable damage popups and kill counter
2. get a kill or just damage an enemy
3. the damage number will be inaccurate and the kill counter will go up by 2
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows 10
* BLT version: superblt 1.3.1
* Other mods installed:
![image](https://user-images.githubusercontent.com/75227863/129382698-052f0dcf-4d8c-4ec2-bf42-6065aac39e65.png)

## BLT log
the log was too long to paste so i'm just attaching it
[2021_08_13_log.txt](https://github.com/jaondayko/WolfHUD/files/6983496/2021_08_13_log.txt)

**Comment by AJAL8000** [comment]
x2

**Comment by jaondayko** [comment]
@jsmoment Can you confirm with me if this is fixed? I am in the belief it is using the most updated version.
