### ISSUE TITLE
Crashing when starting heist

### ISSUE THREAD

**Issue by abeck58** [jaondayko/WolfHUD#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [X] I made sure this issue doesn't persist without this mod
- [X] I checked to make sure that this issue has not already been filed

# Expected Behavior

No crashing

# Current Behavior

Crashing

# Failure Information (for bugs)
When trying to load into a heist the game spends a few seconds loading and then crashes to desktop. I have tried reinstalling and using the original (I can't remember who made it) as well as the Kamikaze94 version and yours all have the exact same behavior
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. select heist
2. press accept 
3. weight a few seconds
4. crash

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows
* BLT version: SuperBLT 1.1.6.0
* Other mods installed: N/A
[crash.txt](https://github.com/jaondayko/WolfHUD/files/6234492/crash.txt)

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:123: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   ----------------------------------------------------------------------

Sat Aug 29 21:45:50 2020

Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:123: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                       atcuf32  (???)     ???                                                 
                       atcuf32  (???)     ???                                                 
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.96.909
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5206]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Sat Aug 29 21:48:45 2020

Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:123: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                       atcuf32  (???)     ???                                                 
                       atcuf32  (???)     ???                                                 
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.96.909
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5206]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Mon Sep 14 20:55:57 2020

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     SleepEx                                             
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                       atcuf32  (???)     ???                                                 
                       atcuf32  (???)     ???                                                 
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:326                   

-------------------------------

System information:
	Application version : 1.96.909
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5206]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Fri Mar 26 22:44:52 2021

Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:123: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Fri Mar 26 22:46:24 2021

Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:123: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Fri Mar 26 22:48:12 2021

Application has crashed: C++ exception
Pure virtual function call

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:326                   

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Fri Mar 26 22:50:42 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     SleepEx                                             
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:326                   

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Fri Mar 26 23:12:12 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:326                   

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Sat Mar 27 09:08:35 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:326                   

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Sat Mar 27 10:26:53 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     SleepEx                                             
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:326                   

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Sat Mar 27 10:30:27 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     SleepEx                                             
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:326                   

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Sat Mar 27 11:14:56 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	Language : english
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : threaded

----------------------------------------------------------------------

Sat Mar 27 11:15:05 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	Language : english
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : threaded

----------------------------------------------------------------------

Sun Mar 28 14:16:45 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	Language : english
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : threaded

----------------------------------------------------------------------

Sun Mar 28 14:17:01 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	Language : english
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : threaded

----------------------------------------------------------------------

Sun Mar 28 14:19:08 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	Language : english
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : threaded

----------------------------------------------------------------------

Wed Mar 31 16:41:46 2021

Application has crashed: C++ exception
[string "lib/managers/hud/hudassaultcorner.lua"]:1008: attempt to index a nil value

SCRIPT STACK

setup_wave_display() lib/managers/hud/hudassaultcorner.lua:198
HUDAssaultCorner_init() lib/managers/hud/hudassaultcorner.lua:89
init_original() @mods/WolfHUD-master/lua/HUDList.lua:6793
init() @mods/WolfHUD-master/lua/AdvAssault.lua:15
new() core/lib/utils/coreclass.lua:35
_create_assault_corner() lib/managers/hudmanagerpd2.lua:719
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:666
_setup_player_info_hud_pd2_original() @mods/WolfHUD-master/lua/HUDList.lua:113
_setup_player_info_hud_pd2() @mods/WolfHUD-master/lua/DrivingHUD.lua:944
setup() 4
setup() lib/managers/hudmanager.lua:330
load_hud() lib/managers/hudmanager.lua:317
init_finalize() lib/managers/hudmanager.lua:219
init_finalize() lib/setups/gamesetup.lua:704
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Wed Mar 31 16:48:09 2021

Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:123: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

----------------------------------------------------------------------

Wed Mar 31 17:06:05 2021

Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:123: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:442

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.102.954
	CPU : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16286MB 416KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (HyperX Virtual Surround Sound))

</details>

**Comment by fatcatonmars** [comment]
Not a developer of any sort, so I can't read the crash log or BLT log, but I can't reproduce any crashing simply by loading a heist, neither online hosting or offline play. Same SuperBLT version and the latest release of this mod branch, no other mods installed. Were you trying to join online as a client? Plenty of host mods will cause client crashes, [TdlQ's Anticrash](http://pd2mods.z77.fr/anticrash.html) is very good at preventing them, I've found.

**Comment by jaondayko** [comment]
Has there been any more information / is this still crashing for you? I would suggest removing both SuperBLT and WolfHUD and retrying to install. It is working on several different PCs for me
