### ISSUE TITLE
Mountain Master crush problem

### ISSUE THREAD

**Issue by shihhsian** [jaondayko/WolfHUD#36]
When we use this hud and shot Yufu Wang (the boss at this map) at loud will cause a crash. 
Please check crashlog ; the problem will be DamageIndicator.
When I delete this Lua file , I fixed the crash.
The same problem happens with Vanillahud (also because the LUA file)

[2022_03_14_log.txt](https://github.com/jaondayko/WolfHUD/files/8245709/2022_03_14_log.txt)
[crashlog.txt](https://github.com/jaondayko/WolfHUD/files/8245719/crashlog.txt)

Best regards.

**Comment by jaondayko** [comment]
Hi there,

Update to the recent version, it should be fixed now.

Thanks!
