### ISSUE TITLE
auto update fail

### ISSUE THREAD

**Issue by AnohitoMag** [jaondayko/WolfHUD#38]
I keep failing update WolfHUD. Log says hashes verify is failed.
What do I do? (sorry for my bad English)
[2022_03_27_log.txt](https://github.com/jaondayko/WolfHUD/files/8357096/2022_03_27_log.txt)

**Comment by Smithienious** [comment]
Looks like someone forgot to merge `master` into `autoupdate`

**Comment by Smithienious** [comment]
@jaondayko @MrDogit can someone push an update to `autoupdate` please?

**Comment by MrDogit** [comment]
> @jaondayko @MrDogit can someone push an update to `autoupdate` please?

Thankyou for ping me. Since today autoupdate work properly.
