### ISSUE TITLE
"Auto-Updates compromised" notice in main menu.

### ISSUE THREAD

**Issue by fatcatonmars** [jaondayko/WolfHUD#4]
![image](https://user-images.githubusercontent.com/31595440/113181079-c87dce80-9227-11eb-8089-fa675e160096.png)

Picture says all. Downloading the most recent update, the folder is mislabeled and causes this notice. Simple fix is changing the folder name like the notice says.

**Comment by jaondayko** [comment]
Sorry about that, should be good now!
