### ISSUE TITLE
Incorrect damage numbers from Enemy Damage Popup and double counting enemy deaths.

### ISSUE THREAD

**Issue by fatcatonmars** [jaondayko/WolfHUD#5]
# Failure Information (for bugs)
## Description

Play a heist with "Enemy Damage Popup" feature turned on and shoot an enemy, damage will be incorrectly reported as double visually (42 damage shown as 84 damage) but the enemies will still take regular damage. Tested on Normal and Overkill, offline and online client.
Additionally, possibly linked to this bug, is another where the kill counter adds 2 enemies per kill rather than 1.

## Context

* Operating System: Windows 10
* BLT version: SuperBLT 1.1.6.0
* Other mods installed: None

## BLT log

<details> 
  <summary>BLT Log</summary>

   02:18:07 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\debug\blt_debug.cpp:124) Command line: "D:\SteamLibrary\steamapps\common\PAYDAY 2\payday2_win32_release.exe"
02:18:07 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\platforms\w32\signatures\signatures.cpp:255) Scanning for signatures in payday2_win32_release.exe
02:18:07 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\platforms\w32\signatures\signatures.cpp:301) Scanned for 56 signatures in 0 milliseconds with 0 cache misses
02:18:07 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:18:10 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:18:10 PM Lua: [BLT] Setup...
02:18:10 PM Lua: [BLT] Loading module: 	BLTLogs
02:18:10 PM Lua: [BLT] Loading module: 	BLTModManager
02:18:10 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:18:10 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:18:10 PM Lua: [BLT] Loading module: 	BLTLocalization
02:18:10 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:18:10 PM Lua: [BLT] Loading mods for state: table: 0x001c8f60
02:18:10 PM Lua: [BLT] Loading mod: base
02:18:10 PM Lua: [BLT] Loading mod: WolfHUD-master
02:18:10 PM Lua: [BLT] Loading mod: _Other
02:18:10 PM Lua: [BLT] Could not read or find mod.txt in _Other
02:18:10 PM Lua: [BLT] Setting up mod: 	base
02:18:10 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:18:10 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:18:10 PM Lua: [BLT] Setup...
02:18:10 PM Lua: [BLT] Loading module: 	BLTLogs
02:18:10 PM Lua: [BLT] Loading module: 	BLTModManager
02:18:10 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:18:10 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:18:10 PM Lua: [BLT] Loading module: 	BLTLocalization
02:18:10 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:18:10 PM Lua: [BLT] Loading mods for state: table: 0x001c8f40
02:18:10 PM Lua: [BLT] Loading mod: base
02:18:10 PM Lua: [BLT] Loading mod: WolfHUD-master
02:18:10 PM Lua: [BLT] Loading mod: _Other
02:18:10 PM Lua: [BLT] Could not read or find mod.txt in _Other
02:18:10 PM Lua: [BLT] Setting up mod: 	base
02:18:10 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:18:10 PM Lua: Loading mod settings : nil
02:18:10 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:18:10 PM Lua: [BLT] Setup...
02:18:10 PM Lua: [BLT] Loading module: 	BLTLogs
02:18:10 PM Lua: [BLT] Loading module: 	BLTModManager
02:18:10 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:18:10 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:18:10 PM Lua: [BLT] Loading module: 	BLTLocalization
02:18:10 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:18:10 PM Lua: [BLT] Loading mods for state: table: 0x2a55ce20
02:18:10 PM Lua: [BLT] Loading mod: base
02:18:10 PM Lua: [BLT] Loading mod: WolfHUD-master
02:18:10 PM Lua: [BLT] Loading mod: _Other
02:18:10 PM Lua: [BLT] Could not read or find mod.txt in _Other
02:18:10 PM Lua: [BLT] Setting up mod: 	base
02:18:10 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:18:16 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:51) CURL_INITD
02:18:18 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:447) Incoming HTTP Request/Request
02:18:18 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:461) https://znix.xyz/paydaymods/updates/meta.php?id=payday2blt - 2453
02:18:18 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:168) Launching Async HTTP Thread
02:18:18 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:447) Incoming HTTP Request/Request
02:18:18 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:461) https://znix.xyz/paydaymods/updates/meta.php?id=payday2bltwsockdll - 2450
02:18:18 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:168) Launching Async HTTP Thread
02:18:18 PM Lua: [Updates] Received update data for 'payday2bltwsockdll'
02:18:18 PM Lua: [Updates] Comparing hash data for payday2bltwsockdll:
Server: 2bde11b432e7684d2aa2bcd06fc4a629dbbde11984f2593c4e692f7d1e5517ee
 Local: 2bde11b432e7684d2aa2bcd06fc4a629dbbde11984f2593c4e692f7d1e5517ee
02:18:18 PM Lua: [Updates] Received update data for 'payday2blt'
02:18:18 PM Lua: [Updates] Comparing hash data for payday2blt:
Server: 8b23e38208d3e31dd13f82c9e9f8e6d2fa2dc4970276177a2dd06033cfb1f44e
 Local: 8b23e38208d3e31dd13f82c9e9f8e6d2fa2dc4970276177a2dd06033cfb1f44e
02:18:28 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:18:28 PM Lua: [BLT] Setup...
02:18:28 PM Lua: [BLT] Loading module: 	BLTLogs
02:18:28 PM Lua: [BLT] Loading module: 	BLTModManager
02:18:28 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:18:28 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:18:28 PM Lua: [BLT] Loading module: 	BLTLocalization
02:18:28 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:18:28 PM Lua: [BLT] Loading mods for state: table: 0x2b6cb780
02:18:28 PM Lua: [BLT] Loading mod: base
02:18:28 PM Lua: [BLT] Loading mod: WolfHUD-master
02:18:28 PM Lua: [BLT] Loading mod: _Other
02:18:28 PM Lua: [BLT] Could not read or find mod.txt in _Other
02:18:28 PM Lua: [BLT] Setting up mod: 	base
02:18:28 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:18:28 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:18:28 PM Lua: [BLT] Setup...
02:18:28 PM Lua: [BLT] Loading module: 	BLTLogs
02:18:28 PM Lua: [BLT] Loading module: 	BLTModManager
02:18:28 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:18:28 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:18:28 PM Lua: [BLT] Loading module: 	BLTLocalization
02:18:28 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:18:28 PM Lua: [BLT] Loading mods for state: table: 0x3a577160
02:18:28 PM Lua: [BLT] Loading mod: base
02:18:28 PM Lua: [BLT] Loading mod: WolfHUD-master
02:18:28 PM Lua: [BLT] Loading mod: _Other
02:18:28 PM Lua: [BLT] Could not read or find mod.txt in _Other
02:18:28 PM Lua: [BLT] Setting up mod: 	base
02:18:28 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:18:28 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:18:28 PM Lua: [BLT] Setup...
02:18:28 PM Lua: [BLT] Loading module: 	BLTLogs
02:18:28 PM Lua: [BLT] Loading module: 	BLTModManager
02:18:28 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:18:28 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:18:28 PM Lua: [BLT] Loading module: 	BLTLocalization
02:18:28 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:18:28 PM Lua: [BLT] Loading mods for state: table: 0x4bfa79a0
02:18:28 PM Lua: [BLT] Loading mod: base
02:18:28 PM Lua: [BLT] Loading mod: WolfHUD-master
02:18:28 PM Lua: [BLT] Loading mod: _Other
02:18:28 PM Lua: [BLT] Could not read or find mod.txt in _Other
02:18:28 PM Lua: [BLT] Setting up mod: 	base
02:18:28 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:18:28 PM Lua: Loading mod settings : nil
02:21:00 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:21:00 PM Lua: [BLT] Setup...
02:21:00 PM Lua: [BLT] Loading module: 	BLTLogs
02:21:00 PM Lua: [BLT] Loading module: 	BLTModManager
02:21:00 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:21:00 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:21:00 PM Lua: [BLT] Loading module: 	BLTLocalization
02:21:00 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:21:00 PM Lua: [BLT] Loading mods for state: table: 0x3c4d90c0
02:21:00 PM Lua: [BLT] Loading mod: base
02:21:00 PM Lua: [BLT] Loading mod: WolfHUD-master
02:21:00 PM Lua: [BLT] Loading mod: _Other
02:21:00 PM Lua: [BLT] Could not read or find mod.txt in _Other
02:21:00 PM Lua: [BLT] Setting up mod: 	base
02:21:00 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:21:01 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
02:21:01 PM Lua: [BLT] Setup...
02:21:01 PM Lua: [BLT] Loading module: 	BLTLogs
02:21:01 PM Lua: [BLT] Loading module: 	BLTModManager
02:21:01 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:21:01 PM Lu

(Not cut off, it ends there.)

</details>

![image](https://user-images.githubusercontent.com/31595440/113330772-7c995b00-92f5-11eb-8a0e-35b8e0f13a6a.png)

**Comment by jaondayko** [comment]
I have added a log to show the damage the player is doing. It appears that the damage is passing through twice? This might explain why you are seeing the double damage AND double kill count. I will look further and update here

> 05:46:46 PM Lua: [WolfHUD] INFO: (GameInfo) Damage logging: 8 - true - false
05:46:46 PM Lua: [WolfHUD] INFO: (GameInfo) Damage logging: 8 - true - false - 80
05:46:46 PM Lua: [WolfHUD] INFO: (GameInfo) Damage logging: 8 - true - false
05:46:46 PM Lua: [WolfHUD] INFO: (GameInfo) Damage logging: 8 - true - false - 160

**Comment by milodakat** [comment]
I also believe it is double counting joker kills

**Comment by Gandalf360one** [comment]
Someone got a solution:

https://github.com/Kamikaze94/WolfHUD/issues/918

**Comment by jaondayko** [comment]
I will merge their solution into the current! I am on vacation currently so am semi away but will merge this in. If it continues let me know! (I will keep this issue open for the next few days for a report if fixed or not)
#6

**Comment by jsmoment** [comment]
this still happens

**Comment by Gandalf360one** [comment]
> 
> 
> this still happens

Nope it is fixed with this WolfHud version
